version: '3'

services:
  backend:
    container_name: backend
    image: kassiopeya3/backend
    env_file: .env 
    ports:  
      - '4000:3000'
    depends_on:
      - postgres
    restart: always
    networks:
      - backend

  frontend:
    container_name: frontend
    image: kassiopeya3/frontend
    env_file:
      - .env
    ports:
      - '80:3000'
    restart: always
    networks:
      - frontend

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file:
      - .env
    restart: always
    volumes:
      - postgres_data:/data/postgres
    networks:
      - backend
  
volumes:
  postgres_data:

networks:
  backend:
  frontend: